#!/bin/sh

cd ..
#Copy implemented hooks 
for file in `ls -1 hooks`
do
 if [ $file != "InstallHooksAndTools" ]; then
   echo $file 
   cp hooks/$file .git/hooks/$file
   sudo chmod +x .git/hooks/$file
 fi
done

#Create directory tools
mkdir -p "tools"

#Create directory artifacts
mkdir -p "artifacts"

cd "tools"

#Install Raptor
if [ ! -d "$Raptor" ]; then

  curl -O http://download.librdf.org/source/raptor2-2.0.15.tar.gz
  
  tar -zxvf raptor2-2.0.15.tar.gz
  mv raptor2-2.0.15 Raptor
  cd Raptor
  
  sudo apt-get install libxml2-dev libxslt1-dev python-dev
  sudo apt-get -y install raptor2-utils
  ./configure
  make
  sudo make install
  cd ..
fi

#Install Owl2VCS
if [ ! -d "$owl2vcs" ]; then

  curl -O https://dl.dropbox.com/u/62722148/owl2vcs-releases/owl2vcs-0.30-bin.zip
  
  unzip owl2vcs-0.30-bin.zip
  mv owl2vcs-0.30-bin owl2vcs
  cd owl2vcs
  
  export PATH=$PATH:$(pwd)
fi

#Download Widoco
if [ ! -e "rdf-toolkit.jar" ]; then
  curl -O https://github.com/vocol/vocol/blob/master/Git4Voc/tools/widoco.jar
fi

#Download Parrot
if [ ! -e "parrot.jar" ]; then
  curl -O https://github.com/vocol/vocol/blob/master/Git4Voc/tools/parrot.jar
fi

#Download RDF-Toolkit
if [ ! -e "rdf-toolkit.jar" ]; then
  curl -O https://github.com/vocol/vocol/blob/master/Git4Voc/tools/rdf-toolkit.jar
fi

#Download EvolutionTemplate
if [ ! -e "templates.zip" ]; then
  curl -O https://github.com/vocol/vocol/blob/master/Git4Voc/tools/templates.zip
  
  unzip templates.zip -d ../artifacts
fi

cd ..

owl2enable

#Ignore tools folder using .gitignore
if [ ! -e ".gitignore" ]; then
  touch .gitignore
  echo "tools/" >> .gitignore
else
  if ! grep -q "tools" ".gitignore"; then
   echo "tools/" >> .gitignore
  fi
fi
