#!/bin/sh

#Copy implemented hooks 
for i in `ls -1 hooks`
do
cp hooks/$i .git/hooks/$i
done

#Create directory for necessary tools

if [ -d "$tools" ]; then
  mkdir "tools" && cd "$_"
else
    cd "tools"
fi

#Install Raptor
if [ -d "$Raptor" ]; then

  curl -O http://download.librdf.org/source/raptor2-2.0.15.tar.gz
  
  tar -zxvf raptor2-2.0.15.tar.gz
  mv raptor2-2.0.15 Raptor
  cd raptor2-2.0.15
  
  sudo apt-get install libxml2-dev libxslt1-dev python-dev
  sudo apt-get -y install raptor2-utils
  ./configure
  make
  sudo make install
  cd ..
fi

#Install Parrot
if [ -d "$Parrot" ]; then
  curl -O https://bitbucket.org/fundacionctic/parrot/get/b07400164540.zip
  unzip b07400164540.zip
  mv b07400164540 Parrot
fi

